### ISSUE TITLE
Removing Effect Dependencies

### ISSUE THREAD

**Issue by r00bal** [KamilSzafranski/goit-react-hw-05-movies#1]
https://github.com/KamilSzafranski/goit-react-hw-05-movies/blob/9ed163356300339d8eb79c635dbe4b4341a0ba08/src/components/Search/Search.jsx#L30

Wyłączanie tej zasady to nie jest dobra praktyka,
https://beta.reactjs.org/learn/removing-effect-dependencies

**Comment by KamilSzafranski** [comment]
Poprawione :)
